# Generated by Django 3.2.6 on 2021-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
