# Generated by Django 3.2.6 on 2021-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_item_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.CharField(blank=True, default='null', max_length=200),
            preserve_default=False,
        ),
    ]
